### ISSUE TITLE
Cannot find hs file

### ISSUE THREAD

**Issue by cannc4** [foxbenjaminfox/require-haskell#1]
Hi, thanks for creating this super useful package. I was looking for a way to compile a timer script and this seems to be doing just what I need. 

However, it doesn't seem to be finding the right path all thought I am pretty sure it's the right path

Any clues on that?

Cheers
C

```
Error: Cannot find module './sync.hs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.resolve (internal/module.js:27:19)
    at requireHaskell (/Users/canince/Documents/Git/Siren/node_modules/require-haskell/require-haskell.js:5:22)
    at Object.<anonymous> (/Users/canince/Documents/Git/Siren/server/app.js:13:14)
    at Module._compile (module.js:573:32)
    at loader (/Users/canince/Documents/Git/Siren/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/canince/Documents/Git/Siren/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/canince/Documents/Git/Siren/server/start.js:5:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
```

**Comment by foxbenjaminfox** [comment]
Well, this package is rather unmaintained. I made it years ago, and I haven't touched it since, and it shows.

The problem here is that [`require.resolve`](https://nodejs.org/api/globals.html#globals_require_resolve) tries to locate your file relative to itself, which in this case means relative to this package. This is not what you want, and is in fact a major bug.

I don't really expect to ever get around to rewriting this package to fix this bug. While I'm glad you consider this to be a super useful package, it really isn't more than a thin wrapper around [`child_process`](https://nodejs.org/api/child_process.html) with just a little bit of syntactic sugar to make it seem like importing a Javascript module.

Here's an example of how to use `child_process` directly:
````js
const child_process = require('child_process')
child_process.exec('runhaskell ./sync.hs', function (err, stdout, stderr) {
   // ...
})
````

It's not much different than using this package, except without the syntactic sugar of a `require`-like interface.
